/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package open_cluster_management.io;

import open_cluster_management.ApiException;
import open_cluster_management.io.IoK8sApimachineryPkgApisMetaV1DeleteOptions;
import open_cluster_management.io.IoK8sApimachineryPkgApisMetaV1Patch;
import open_cluster_management.io.IoK8sApimachineryPkgApisMetaV1Status;
import open_cluster_management.io.IoOpenClusterManagementInventoryV1alpha1BareMetalAsset;
import open_cluster_management.io.IoOpenClusterManagementInventoryV1alpha1BareMetalAssetList;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InventoryOpenClusterManagementIoV1alpha1Api
 */
@Ignore
public class InventoryOpenClusterManagementIoV1alpha1ApiTest {

    private final InventoryOpenClusterManagementIoV1alpha1Api api = new InventoryOpenClusterManagementIoV1alpha1Api();

    
    /**
     * 
     *
     * create a BareMetalAsset
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createInventoryOpenClusterManagementIoV1alpha1NamespacedBareMetalAssetTest() throws ApiException {
        String namespace = null;
        IoOpenClusterManagementInventoryV1alpha1BareMetalAsset body = null;
        String pretty = null;
        String dryRun = null;
        String fieldManager = null;
        IoOpenClusterManagementInventoryV1alpha1BareMetalAsset response = api.createInventoryOpenClusterManagementIoV1alpha1NamespacedBareMetalAsset(namespace, body, pretty, dryRun, fieldManager);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * delete collection of BareMetalAsset
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteInventoryOpenClusterManagementIoV1alpha1CollectionNamespacedBareMetalAssetTest() throws ApiException {
        String namespace = null;
        String pretty = null;
        Boolean allowWatchBookmarks = null;
        String _continue = null;
        String fieldSelector = null;
        String labelSelector = null;
        Integer limit = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        IoK8sApimachineryPkgApisMetaV1Status response = api.deleteInventoryOpenClusterManagementIoV1alpha1CollectionNamespacedBareMetalAsset(namespace, pretty, allowWatchBookmarks, _continue, fieldSelector, labelSelector, limit, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * delete a BareMetalAsset
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteInventoryOpenClusterManagementIoV1alpha1NamespacedBareMetalAssetTest() throws ApiException {
        String name = null;
        String namespace = null;
        String pretty = null;
        IoK8sApimachineryPkgApisMetaV1DeleteOptions body = null;
        String dryRun = null;
        Integer gracePeriodSeconds = null;
        Boolean orphanDependents = null;
        String propagationPolicy = null;
        IoK8sApimachineryPkgApisMetaV1Status response = api.deleteInventoryOpenClusterManagementIoV1alpha1NamespacedBareMetalAsset(name, namespace, pretty, body, dryRun, gracePeriodSeconds, orphanDependents, propagationPolicy);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * list objects of kind BareMetalAsset
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listInventoryOpenClusterManagementIoV1alpha1BareMetalAssetForAllNamespacesTest() throws ApiException {
        Boolean allowWatchBookmarks = null;
        String _continue = null;
        String fieldSelector = null;
        String labelSelector = null;
        Integer limit = null;
        String pretty = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        IoOpenClusterManagementInventoryV1alpha1BareMetalAssetList response = api.listInventoryOpenClusterManagementIoV1alpha1BareMetalAssetForAllNamespaces(allowWatchBookmarks, _continue, fieldSelector, labelSelector, limit, pretty, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * list objects of kind BareMetalAsset
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listInventoryOpenClusterManagementIoV1alpha1NamespacedBareMetalAssetTest() throws ApiException {
        String namespace = null;
        String pretty = null;
        Boolean allowWatchBookmarks = null;
        String _continue = null;
        String fieldSelector = null;
        String labelSelector = null;
        Integer limit = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        IoOpenClusterManagementInventoryV1alpha1BareMetalAssetList response = api.listInventoryOpenClusterManagementIoV1alpha1NamespacedBareMetalAsset(namespace, pretty, allowWatchBookmarks, _continue, fieldSelector, labelSelector, limit, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * partially update the specified BareMetalAsset
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchInventoryOpenClusterManagementIoV1alpha1NamespacedBareMetalAssetTest() throws ApiException {
        String name = null;
        String namespace = null;
        IoK8sApimachineryPkgApisMetaV1Patch body = null;
        String pretty = null;
        String dryRun = null;
        String fieldManager = null;
        IoOpenClusterManagementInventoryV1alpha1BareMetalAsset response = api.patchInventoryOpenClusterManagementIoV1alpha1NamespacedBareMetalAsset(name, namespace, body, pretty, dryRun, fieldManager);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * partially update status of the specified BareMetalAsset
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchInventoryOpenClusterManagementIoV1alpha1NamespacedBareMetalAssetStatusTest() throws ApiException {
        String name = null;
        String namespace = null;
        IoK8sApimachineryPkgApisMetaV1Patch body = null;
        String pretty = null;
        String dryRun = null;
        String fieldManager = null;
        IoOpenClusterManagementInventoryV1alpha1BareMetalAsset response = api.patchInventoryOpenClusterManagementIoV1alpha1NamespacedBareMetalAssetStatus(name, namespace, body, pretty, dryRun, fieldManager);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * read the specified BareMetalAsset
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readInventoryOpenClusterManagementIoV1alpha1NamespacedBareMetalAssetTest() throws ApiException {
        String name = null;
        String namespace = null;
        String pretty = null;
        String resourceVersion = null;
        IoOpenClusterManagementInventoryV1alpha1BareMetalAsset response = api.readInventoryOpenClusterManagementIoV1alpha1NamespacedBareMetalAsset(name, namespace, pretty, resourceVersion);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * read status of the specified BareMetalAsset
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readInventoryOpenClusterManagementIoV1alpha1NamespacedBareMetalAssetStatusTest() throws ApiException {
        String name = null;
        String namespace = null;
        String pretty = null;
        String resourceVersion = null;
        IoOpenClusterManagementInventoryV1alpha1BareMetalAsset response = api.readInventoryOpenClusterManagementIoV1alpha1NamespacedBareMetalAssetStatus(name, namespace, pretty, resourceVersion);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * replace the specified BareMetalAsset
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replaceInventoryOpenClusterManagementIoV1alpha1NamespacedBareMetalAssetTest() throws ApiException {
        String name = null;
        String namespace = null;
        IoOpenClusterManagementInventoryV1alpha1BareMetalAsset body = null;
        String pretty = null;
        String dryRun = null;
        String fieldManager = null;
        IoOpenClusterManagementInventoryV1alpha1BareMetalAsset response = api.replaceInventoryOpenClusterManagementIoV1alpha1NamespacedBareMetalAsset(name, namespace, body, pretty, dryRun, fieldManager);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * replace status of the specified BareMetalAsset
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replaceInventoryOpenClusterManagementIoV1alpha1NamespacedBareMetalAssetStatusTest() throws ApiException {
        String name = null;
        String namespace = null;
        IoOpenClusterManagementInventoryV1alpha1BareMetalAsset body = null;
        String pretty = null;
        String dryRun = null;
        String fieldManager = null;
        IoOpenClusterManagementInventoryV1alpha1BareMetalAsset response = api.replaceInventoryOpenClusterManagementIoV1alpha1NamespacedBareMetalAssetStatus(name, namespace, body, pretty, dryRun, fieldManager);

        // TODO: test validations
    }
    
}
