/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package open_cluster_management.io;

import open_cluster_management.ApiException;
import open_cluster_management.io.ComGithubOperatorFrameworkOperatorLifecycleManagerPkgPackageServerApisOperatorsV1PackageManifest;
import open_cluster_management.io.ComGithubOperatorFrameworkOperatorLifecycleManagerPkgPackageServerApisOperatorsV1PackageManifestList;
import open_cluster_management.io.IoK8sApimachineryPkgApisMetaV1APIResourceList;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PackagesOperatorsCoreosComV1Api
 */
@Ignore
public class PackagesOperatorsCoreosComV1ApiTest {

    private final PackagesOperatorsCoreosComV1Api api = new PackagesOperatorsCoreosComV1Api();

    
    /**
     * 
     *
     * connect GET requests to icon of PackageManifest
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void connectPackagesOperatorsCoreosComV1GetNamespacedPackageManifestIconTest() throws ApiException {
        String name = null;
        String namespace = null;
        String response = api.connectPackagesOperatorsCoreosComV1GetNamespacedPackageManifestIcon(name, namespace);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * get available resources
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPackagesOperatorsCoreosComV1APIResourcesTest() throws ApiException {
        IoK8sApimachineryPkgApisMetaV1APIResourceList response = api.getPackagesOperatorsCoreosComV1APIResources();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * list objects of kind PackageManifest
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listPackagesOperatorsCoreosComV1NamespacedPackageManifestTest() throws ApiException {
        String namespace = null;
        Boolean allowWatchBookmarks = null;
        String _continue = null;
        String fieldSelector = null;
        String labelSelector = null;
        Integer limit = null;
        String pretty = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        ComGithubOperatorFrameworkOperatorLifecycleManagerPkgPackageServerApisOperatorsV1PackageManifestList response = api.listPackagesOperatorsCoreosComV1NamespacedPackageManifest(namespace, allowWatchBookmarks, _continue, fieldSelector, labelSelector, limit, pretty, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * list objects of kind PackageManifest
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listPackagesOperatorsCoreosComV1PackageManifestForAllNamespacesTest() throws ApiException {
        Boolean allowWatchBookmarks = null;
        String _continue = null;
        String fieldSelector = null;
        String labelSelector = null;
        Integer limit = null;
        String pretty = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        ComGithubOperatorFrameworkOperatorLifecycleManagerPkgPackageServerApisOperatorsV1PackageManifestList response = api.listPackagesOperatorsCoreosComV1PackageManifestForAllNamespaces(allowWatchBookmarks, _continue, fieldSelector, labelSelector, limit, pretty, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * read the specified PackageManifest
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readPackagesOperatorsCoreosComV1NamespacedPackageManifestTest() throws ApiException {
        String name = null;
        String namespace = null;
        String pretty = null;
        ComGithubOperatorFrameworkOperatorLifecycleManagerPkgPackageServerApisOperatorsV1PackageManifest response = api.readPackagesOperatorsCoreosComV1NamespacedPackageManifest(name, namespace, pretty);

        // TODO: test validations
    }
    
}
