/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package open_cluster_management.io;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import open_cluster_management.io.ComCoreosOperatorsV1CatalogSourceConfigStatusCurrentPhase;

/**
 * CatalogSourceConfigStatus defines the observed state of CatalogSourceConfig
 */
@ApiModel(description = "CatalogSourceConfigStatus defines the observed state of CatalogSourceConfig")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-18T17:27:50.678+03:00")
public class ComCoreosOperatorsV1CatalogSourceConfigStatus {
  @SerializedName("currentPhase")
  private ComCoreosOperatorsV1CatalogSourceConfigStatusCurrentPhase currentPhase = null;

  @SerializedName("packageRepositioryVersions")
  private Map<String, String> packageRepositioryVersions = null;

  public ComCoreosOperatorsV1CatalogSourceConfigStatus currentPhase(ComCoreosOperatorsV1CatalogSourceConfigStatusCurrentPhase currentPhase) {
    this.currentPhase = currentPhase;
    return this;
  }

   /**
   * Get currentPhase
   * @return currentPhase
  **/
  @ApiModelProperty(value = "")
  public ComCoreosOperatorsV1CatalogSourceConfigStatusCurrentPhase getCurrentPhase() {
    return currentPhase;
  }

  public void setCurrentPhase(ComCoreosOperatorsV1CatalogSourceConfigStatusCurrentPhase currentPhase) {
    this.currentPhase = currentPhase;
  }

  public ComCoreosOperatorsV1CatalogSourceConfigStatus packageRepositioryVersions(Map<String, String> packageRepositioryVersions) {
    this.packageRepositioryVersions = packageRepositioryVersions;
    return this;
  }

  public ComCoreosOperatorsV1CatalogSourceConfigStatus putPackageRepositioryVersionsItem(String key, String packageRepositioryVersionsItem) {
    if (this.packageRepositioryVersions == null) {
      this.packageRepositioryVersions = new HashMap<>();
    }
    this.packageRepositioryVersions.put(key, packageRepositioryVersionsItem);
    return this;
  }

   /**
   * Map of packages (key) and their app registry package version (value)
   * @return packageRepositioryVersions
  **/
  @ApiModelProperty(value = "Map of packages (key) and their app registry package version (value)")
  public Map<String, String> getPackageRepositioryVersions() {
    return packageRepositioryVersions;
  }

  public void setPackageRepositioryVersions(Map<String, String> packageRepositioryVersions) {
    this.packageRepositioryVersions = packageRepositioryVersions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComCoreosOperatorsV1CatalogSourceConfigStatus comCoreosOperatorsV1CatalogSourceConfigStatus = (ComCoreosOperatorsV1CatalogSourceConfigStatus) o;
    return Objects.equals(this.currentPhase, comCoreosOperatorsV1CatalogSourceConfigStatus.currentPhase) &&
        Objects.equals(this.packageRepositioryVersions, comCoreosOperatorsV1CatalogSourceConfigStatus.packageRepositioryVersions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currentPhase, packageRepositioryVersions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComCoreosOperatorsV1CatalogSourceConfigStatus {\n");
    
    sb.append("    currentPhase: ").append(toIndentedString(currentPhase)).append("\n");
    sb.append("    packageRepositioryVersions: ").append(toIndentedString(packageRepositioryVersions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

