/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package open_cluster_management.io;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import open_cluster_management.io.IoK8sApimachineryPkgApisMetaV1ObjectMetaV2;

/**
 * OAuthAuthorizeToken describes an OAuth authorization token
 */
@ApiModel(description = "OAuthAuthorizeToken describes an OAuth authorization token")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-18T17:27:50.678+03:00")
public class ComGithubOpenshiftApiOauthV1OAuthAuthorizeToken {
  @SerializedName("apiVersion")
  private String apiVersion = null;

  @SerializedName("clientName")
  private String clientName = null;

  @SerializedName("codeChallenge")
  private String codeChallenge = null;

  @SerializedName("codeChallengeMethod")
  private String codeChallengeMethod = null;

  @SerializedName("expiresIn")
  private Long expiresIn = null;

  @SerializedName("kind")
  private String kind = null;

  @SerializedName("metadata")
  private IoK8sApimachineryPkgApisMetaV1ObjectMetaV2 metadata = null;

  @SerializedName("redirectURI")
  private String redirectURI = null;

  @SerializedName("scopes")
  private List<String> scopes = null;

  @SerializedName("state")
  private String state = null;

  @SerializedName("userName")
  private String userName = null;

  @SerializedName("userUID")
  private String userUID = null;

  public ComGithubOpenshiftApiOauthV1OAuthAuthorizeToken apiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
    return this;
  }

   /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   * @return apiVersion
  **/
  @ApiModelProperty(value = "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources")
  public String getApiVersion() {
    return apiVersion;
  }

  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }

  public ComGithubOpenshiftApiOauthV1OAuthAuthorizeToken clientName(String clientName) {
    this.clientName = clientName;
    return this;
  }

   /**
   * ClientName references the client that created this token.
   * @return clientName
  **/
  @ApiModelProperty(value = "ClientName references the client that created this token.")
  public String getClientName() {
    return clientName;
  }

  public void setClientName(String clientName) {
    this.clientName = clientName;
  }

  public ComGithubOpenshiftApiOauthV1OAuthAuthorizeToken codeChallenge(String codeChallenge) {
    this.codeChallenge = codeChallenge;
    return this;
  }

   /**
   * CodeChallenge is the optional code_challenge associated with this authorization code, as described in rfc7636
   * @return codeChallenge
  **/
  @ApiModelProperty(value = "CodeChallenge is the optional code_challenge associated with this authorization code, as described in rfc7636")
  public String getCodeChallenge() {
    return codeChallenge;
  }

  public void setCodeChallenge(String codeChallenge) {
    this.codeChallenge = codeChallenge;
  }

  public ComGithubOpenshiftApiOauthV1OAuthAuthorizeToken codeChallengeMethod(String codeChallengeMethod) {
    this.codeChallengeMethod = codeChallengeMethod;
    return this;
  }

   /**
   * CodeChallengeMethod is the optional code_challenge_method associated with this authorization code, as described in rfc7636
   * @return codeChallengeMethod
  **/
  @ApiModelProperty(value = "CodeChallengeMethod is the optional code_challenge_method associated with this authorization code, as described in rfc7636")
  public String getCodeChallengeMethod() {
    return codeChallengeMethod;
  }

  public void setCodeChallengeMethod(String codeChallengeMethod) {
    this.codeChallengeMethod = codeChallengeMethod;
  }

  public ComGithubOpenshiftApiOauthV1OAuthAuthorizeToken expiresIn(Long expiresIn) {
    this.expiresIn = expiresIn;
    return this;
  }

   /**
   * ExpiresIn is the seconds from CreationTime before this token expires.
   * @return expiresIn
  **/
  @ApiModelProperty(value = "ExpiresIn is the seconds from CreationTime before this token expires.")
  public Long getExpiresIn() {
    return expiresIn;
  }

  public void setExpiresIn(Long expiresIn) {
    this.expiresIn = expiresIn;
  }

  public ComGithubOpenshiftApiOauthV1OAuthAuthorizeToken kind(String kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   * @return kind
  **/
  @ApiModelProperty(value = "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds")
  public String getKind() {
    return kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }

  public ComGithubOpenshiftApiOauthV1OAuthAuthorizeToken metadata(IoK8sApimachineryPkgApisMetaV1ObjectMetaV2 metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @ApiModelProperty(value = "")
  public IoK8sApimachineryPkgApisMetaV1ObjectMetaV2 getMetadata() {
    return metadata;
  }

  public void setMetadata(IoK8sApimachineryPkgApisMetaV1ObjectMetaV2 metadata) {
    this.metadata = metadata;
  }

  public ComGithubOpenshiftApiOauthV1OAuthAuthorizeToken redirectURI(String redirectURI) {
    this.redirectURI = redirectURI;
    return this;
  }

   /**
   * RedirectURI is the redirection associated with the token.
   * @return redirectURI
  **/
  @ApiModelProperty(value = "RedirectURI is the redirection associated with the token.")
  public String getRedirectURI() {
    return redirectURI;
  }

  public void setRedirectURI(String redirectURI) {
    this.redirectURI = redirectURI;
  }

  public ComGithubOpenshiftApiOauthV1OAuthAuthorizeToken scopes(List<String> scopes) {
    this.scopes = scopes;
    return this;
  }

  public ComGithubOpenshiftApiOauthV1OAuthAuthorizeToken addScopesItem(String scopesItem) {
    if (this.scopes == null) {
      this.scopes = new ArrayList<>();
    }
    this.scopes.add(scopesItem);
    return this;
  }

   /**
   * Scopes is an array of the requested scopes.
   * @return scopes
  **/
  @ApiModelProperty(value = "Scopes is an array of the requested scopes.")
  public List<String> getScopes() {
    return scopes;
  }

  public void setScopes(List<String> scopes) {
    this.scopes = scopes;
  }

  public ComGithubOpenshiftApiOauthV1OAuthAuthorizeToken state(String state) {
    this.state = state;
    return this;
  }

   /**
   * State data from request
   * @return state
  **/
  @ApiModelProperty(value = "State data from request")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public ComGithubOpenshiftApiOauthV1OAuthAuthorizeToken userName(String userName) {
    this.userName = userName;
    return this;
  }

   /**
   * UserName is the user name associated with this token
   * @return userName
  **/
  @ApiModelProperty(value = "UserName is the user name associated with this token")
  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public ComGithubOpenshiftApiOauthV1OAuthAuthorizeToken userUID(String userUID) {
    this.userUID = userUID;
    return this;
  }

   /**
   * UserUID is the unique UID associated with this token. UserUID and UserName must both match for this token to be valid.
   * @return userUID
  **/
  @ApiModelProperty(value = "UserUID is the unique UID associated with this token. UserUID and UserName must both match for this token to be valid.")
  public String getUserUID() {
    return userUID;
  }

  public void setUserUID(String userUID) {
    this.userUID = userUID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubOpenshiftApiOauthV1OAuthAuthorizeToken comGithubOpenshiftApiOauthV1OAuthAuthorizeToken = (ComGithubOpenshiftApiOauthV1OAuthAuthorizeToken) o;
    return Objects.equals(this.apiVersion, comGithubOpenshiftApiOauthV1OAuthAuthorizeToken.apiVersion) &&
        Objects.equals(this.clientName, comGithubOpenshiftApiOauthV1OAuthAuthorizeToken.clientName) &&
        Objects.equals(this.codeChallenge, comGithubOpenshiftApiOauthV1OAuthAuthorizeToken.codeChallenge) &&
        Objects.equals(this.codeChallengeMethod, comGithubOpenshiftApiOauthV1OAuthAuthorizeToken.codeChallengeMethod) &&
        Objects.equals(this.expiresIn, comGithubOpenshiftApiOauthV1OAuthAuthorizeToken.expiresIn) &&
        Objects.equals(this.kind, comGithubOpenshiftApiOauthV1OAuthAuthorizeToken.kind) &&
        Objects.equals(this.metadata, comGithubOpenshiftApiOauthV1OAuthAuthorizeToken.metadata) &&
        Objects.equals(this.redirectURI, comGithubOpenshiftApiOauthV1OAuthAuthorizeToken.redirectURI) &&
        Objects.equals(this.scopes, comGithubOpenshiftApiOauthV1OAuthAuthorizeToken.scopes) &&
        Objects.equals(this.state, comGithubOpenshiftApiOauthV1OAuthAuthorizeToken.state) &&
        Objects.equals(this.userName, comGithubOpenshiftApiOauthV1OAuthAuthorizeToken.userName) &&
        Objects.equals(this.userUID, comGithubOpenshiftApiOauthV1OAuthAuthorizeToken.userUID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiVersion, clientName, codeChallenge, codeChallengeMethod, expiresIn, kind, metadata, redirectURI, scopes, state, userName, userUID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubOpenshiftApiOauthV1OAuthAuthorizeToken {\n");
    
    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    clientName: ").append(toIndentedString(clientName)).append("\n");
    sb.append("    codeChallenge: ").append(toIndentedString(codeChallenge)).append("\n");
    sb.append("    codeChallengeMethod: ").append(toIndentedString(codeChallengeMethod)).append("\n");
    sb.append("    expiresIn: ").append(toIndentedString(expiresIn)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    redirectURI: ").append(toIndentedString(redirectURI)).append("\n");
    sb.append("    scopes: ").append(toIndentedString(scopes)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    userUID: ").append(toIndentedString(userUID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

