/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package open_cluster_management.io;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import open_cluster_management.io.ComGithubOpenshiftApiAuthorizationV1PolicyRule;
import open_cluster_management.io.IoK8sApiRbacV1AggregationRule;
import open_cluster_management.io.IoK8sApimachineryPkgApisMetaV1ObjectMetaV2;

/**
 * ClusterRole is a logical grouping of PolicyRules that can be referenced as a unit by ClusterRoleBindings.
 */
@ApiModel(description = "ClusterRole is a logical grouping of PolicyRules that can be referenced as a unit by ClusterRoleBindings.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-18T17:27:50.678+03:00")
public class ComGithubOpenshiftApiAuthorizationV1ClusterRole {
  @SerializedName("aggregationRule")
  private IoK8sApiRbacV1AggregationRule aggregationRule = null;

  @SerializedName("apiVersion")
  private String apiVersion = null;

  @SerializedName("kind")
  private String kind = null;

  @SerializedName("metadata")
  private IoK8sApimachineryPkgApisMetaV1ObjectMetaV2 metadata = null;

  @SerializedName("rules")
  private List<ComGithubOpenshiftApiAuthorizationV1PolicyRule> rules = new ArrayList<>();

  public ComGithubOpenshiftApiAuthorizationV1ClusterRole aggregationRule(IoK8sApiRbacV1AggregationRule aggregationRule) {
    this.aggregationRule = aggregationRule;
    return this;
  }

   /**
   * AggregationRule is an optional field that describes how to build the Rules for this ClusterRole. If AggregationRule is set, then the Rules are controller managed and direct changes to Rules will be stomped by the controller.
   * @return aggregationRule
  **/
  @ApiModelProperty(value = "AggregationRule is an optional field that describes how to build the Rules for this ClusterRole. If AggregationRule is set, then the Rules are controller managed and direct changes to Rules will be stomped by the controller.")
  public IoK8sApiRbacV1AggregationRule getAggregationRule() {
    return aggregationRule;
  }

  public void setAggregationRule(IoK8sApiRbacV1AggregationRule aggregationRule) {
    this.aggregationRule = aggregationRule;
  }

  public ComGithubOpenshiftApiAuthorizationV1ClusterRole apiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
    return this;
  }

   /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   * @return apiVersion
  **/
  @ApiModelProperty(value = "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources")
  public String getApiVersion() {
    return apiVersion;
  }

  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }

  public ComGithubOpenshiftApiAuthorizationV1ClusterRole kind(String kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   * @return kind
  **/
  @ApiModelProperty(value = "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds")
  public String getKind() {
    return kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }

  public ComGithubOpenshiftApiAuthorizationV1ClusterRole metadata(IoK8sApimachineryPkgApisMetaV1ObjectMetaV2 metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @ApiModelProperty(value = "")
  public IoK8sApimachineryPkgApisMetaV1ObjectMetaV2 getMetadata() {
    return metadata;
  }

  public void setMetadata(IoK8sApimachineryPkgApisMetaV1ObjectMetaV2 metadata) {
    this.metadata = metadata;
  }

  public ComGithubOpenshiftApiAuthorizationV1ClusterRole rules(List<ComGithubOpenshiftApiAuthorizationV1PolicyRule> rules) {
    this.rules = rules;
    return this;
  }

  public ComGithubOpenshiftApiAuthorizationV1ClusterRole addRulesItem(ComGithubOpenshiftApiAuthorizationV1PolicyRule rulesItem) {
    this.rules.add(rulesItem);
    return this;
  }

   /**
   * Rules holds all the PolicyRules for this ClusterRole
   * @return rules
  **/
  @ApiModelProperty(required = true, value = "Rules holds all the PolicyRules for this ClusterRole")
  public List<ComGithubOpenshiftApiAuthorizationV1PolicyRule> getRules() {
    return rules;
  }

  public void setRules(List<ComGithubOpenshiftApiAuthorizationV1PolicyRule> rules) {
    this.rules = rules;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubOpenshiftApiAuthorizationV1ClusterRole comGithubOpenshiftApiAuthorizationV1ClusterRole = (ComGithubOpenshiftApiAuthorizationV1ClusterRole) o;
    return Objects.equals(this.aggregationRule, comGithubOpenshiftApiAuthorizationV1ClusterRole.aggregationRule) &&
        Objects.equals(this.apiVersion, comGithubOpenshiftApiAuthorizationV1ClusterRole.apiVersion) &&
        Objects.equals(this.kind, comGithubOpenshiftApiAuthorizationV1ClusterRole.kind) &&
        Objects.equals(this.metadata, comGithubOpenshiftApiAuthorizationV1ClusterRole.metadata) &&
        Objects.equals(this.rules, comGithubOpenshiftApiAuthorizationV1ClusterRole.rules);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aggregationRule, apiVersion, kind, metadata, rules);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubOpenshiftApiAuthorizationV1ClusterRole {\n");
    
    sb.append("    aggregationRule: ").append(toIndentedString(aggregationRule)).append("\n");
    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

