/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package open_cluster_management.io;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import open_cluster_management.io.ComGithubOperatorFrameworkOperatorLifecycleManagerPkgPackageServerApisOperatorsV1CSVDescription;

/**
 * PackageChannel defines a single channel under a package, pointing to a version of that package.
 */
@ApiModel(description = "PackageChannel defines a single channel under a package, pointing to a version of that package.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-18T17:27:50.678+03:00")
public class ComGithubOperatorFrameworkOperatorLifecycleManagerPkgPackageServerApisOperatorsV1PackageChannel {
  @SerializedName("currentCSV")
  private String currentCSV = null;

  @SerializedName("currentCSVDesc")
  private ComGithubOperatorFrameworkOperatorLifecycleManagerPkgPackageServerApisOperatorsV1CSVDescription currentCSVDesc = null;

  @SerializedName("name")
  private String name = null;

  public ComGithubOperatorFrameworkOperatorLifecycleManagerPkgPackageServerApisOperatorsV1PackageChannel currentCSV(String currentCSV) {
    this.currentCSV = currentCSV;
    return this;
  }

   /**
   * CurrentCSV defines a reference to the CSV holding the version of this package currently for the channel.
   * @return currentCSV
  **/
  @ApiModelProperty(required = true, value = "CurrentCSV defines a reference to the CSV holding the version of this package currently for the channel.")
  public String getCurrentCSV() {
    return currentCSV;
  }

  public void setCurrentCSV(String currentCSV) {
    this.currentCSV = currentCSV;
  }

  public ComGithubOperatorFrameworkOperatorLifecycleManagerPkgPackageServerApisOperatorsV1PackageChannel currentCSVDesc(ComGithubOperatorFrameworkOperatorLifecycleManagerPkgPackageServerApisOperatorsV1CSVDescription currentCSVDesc) {
    this.currentCSVDesc = currentCSVDesc;
    return this;
  }

   /**
   * CurrentCSVSpec holds the spec of the current CSV
   * @return currentCSVDesc
  **/
  @ApiModelProperty(value = "CurrentCSVSpec holds the spec of the current CSV")
  public ComGithubOperatorFrameworkOperatorLifecycleManagerPkgPackageServerApisOperatorsV1CSVDescription getCurrentCSVDesc() {
    return currentCSVDesc;
  }

  public void setCurrentCSVDesc(ComGithubOperatorFrameworkOperatorLifecycleManagerPkgPackageServerApisOperatorsV1CSVDescription currentCSVDesc) {
    this.currentCSVDesc = currentCSVDesc;
  }

  public ComGithubOperatorFrameworkOperatorLifecycleManagerPkgPackageServerApisOperatorsV1PackageChannel name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name is the name of the channel, e.g. &#x60;alpha&#x60; or &#x60;stable&#x60;
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Name is the name of the channel, e.g. `alpha` or `stable`")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubOperatorFrameworkOperatorLifecycleManagerPkgPackageServerApisOperatorsV1PackageChannel comGithubOperatorFrameworkOperatorLifecycleManagerPkgPackageServerApisOperatorsV1PackageChannel = (ComGithubOperatorFrameworkOperatorLifecycleManagerPkgPackageServerApisOperatorsV1PackageChannel) o;
    return Objects.equals(this.currentCSV, comGithubOperatorFrameworkOperatorLifecycleManagerPkgPackageServerApisOperatorsV1PackageChannel.currentCSV) &&
        Objects.equals(this.currentCSVDesc, comGithubOperatorFrameworkOperatorLifecycleManagerPkgPackageServerApisOperatorsV1PackageChannel.currentCSVDesc) &&
        Objects.equals(this.name, comGithubOperatorFrameworkOperatorLifecycleManagerPkgPackageServerApisOperatorsV1PackageChannel.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currentCSV, currentCSVDesc, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubOperatorFrameworkOperatorLifecycleManagerPkgPackageServerApisOperatorsV1PackageChannel {\n");
    
    sb.append("    currentCSV: ").append(toIndentedString(currentCSV)).append("\n");
    sb.append("    currentCSVDesc: ").append(toIndentedString(currentCSVDesc)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

