/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package open_cluster_management.io;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ClusterCondition contains condition information for a cluster.
 */
@ApiModel(description = "ClusterCondition contains condition information for a cluster.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-18T17:27:50.678+03:00")
public class ComGithubOpenClusterManagementMulticloudOperatorsFoundationPkgApisClusterregistryV1alpha1ClusterCondition {
  @SerializedName("lastHeartbeatTime")
  private String lastHeartbeatTime = null;

  @SerializedName("lastTransitionTime")
  private String lastTransitionTime = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("reason")
  private String reason = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("type")
  private String type = null;

  public ComGithubOpenClusterManagementMulticloudOperatorsFoundationPkgApisClusterregistryV1alpha1ClusterCondition lastHeartbeatTime(String lastHeartbeatTime) {
    this.lastHeartbeatTime = lastHeartbeatTime;
    return this;
  }

   /**
   * LastHeartbeatTime is the last time this condition was updated.
   * @return lastHeartbeatTime
  **/
  @ApiModelProperty(value = "LastHeartbeatTime is the last time this condition was updated.")
  public String getLastHeartbeatTime() {
    return lastHeartbeatTime;
  }

  public void setLastHeartbeatTime(String lastHeartbeatTime) {
    this.lastHeartbeatTime = lastHeartbeatTime;
  }

  public ComGithubOpenClusterManagementMulticloudOperatorsFoundationPkgApisClusterregistryV1alpha1ClusterCondition lastTransitionTime(String lastTransitionTime) {
    this.lastTransitionTime = lastTransitionTime;
    return this;
  }

   /**
   * LastTransitionTime is the last time the condition changed from one status to another.
   * @return lastTransitionTime
  **/
  @ApiModelProperty(value = "LastTransitionTime is the last time the condition changed from one status to another.")
  public String getLastTransitionTime() {
    return lastTransitionTime;
  }

  public void setLastTransitionTime(String lastTransitionTime) {
    this.lastTransitionTime = lastTransitionTime;
  }

  public ComGithubOpenClusterManagementMulticloudOperatorsFoundationPkgApisClusterregistryV1alpha1ClusterCondition message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Message is a human-readable message indicating details about the last status change.
   * @return message
  **/
  @ApiModelProperty(value = "Message is a human-readable message indicating details about the last status change.")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public ComGithubOpenClusterManagementMulticloudOperatorsFoundationPkgApisClusterregistryV1alpha1ClusterCondition reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Reason is a (brief) reason for the condition&#39;s last status change.
   * @return reason
  **/
  @ApiModelProperty(value = "Reason is a (brief) reason for the condition's last status change.")
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public ComGithubOpenClusterManagementMulticloudOperatorsFoundationPkgApisClusterregistryV1alpha1ClusterCondition status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Status is the status of the condition. One of True, False, Unknown.
   * @return status
  **/
  @ApiModelProperty(required = true, value = "Status is the status of the condition. One of True, False, Unknown.")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public ComGithubOpenClusterManagementMulticloudOperatorsFoundationPkgApisClusterregistryV1alpha1ClusterCondition type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type is the type of the cluster condition.
   * @return type
  **/
  @ApiModelProperty(required = true, value = "Type is the type of the cluster condition.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubOpenClusterManagementMulticloudOperatorsFoundationPkgApisClusterregistryV1alpha1ClusterCondition comGithubOpenClusterManagementMulticloudOperatorsFoundationPkgApisClusterregistryV1alpha1ClusterCondition = (ComGithubOpenClusterManagementMulticloudOperatorsFoundationPkgApisClusterregistryV1alpha1ClusterCondition) o;
    return Objects.equals(this.lastHeartbeatTime, comGithubOpenClusterManagementMulticloudOperatorsFoundationPkgApisClusterregistryV1alpha1ClusterCondition.lastHeartbeatTime) &&
        Objects.equals(this.lastTransitionTime, comGithubOpenClusterManagementMulticloudOperatorsFoundationPkgApisClusterregistryV1alpha1ClusterCondition.lastTransitionTime) &&
        Objects.equals(this.message, comGithubOpenClusterManagementMulticloudOperatorsFoundationPkgApisClusterregistryV1alpha1ClusterCondition.message) &&
        Objects.equals(this.reason, comGithubOpenClusterManagementMulticloudOperatorsFoundationPkgApisClusterregistryV1alpha1ClusterCondition.reason) &&
        Objects.equals(this.status, comGithubOpenClusterManagementMulticloudOperatorsFoundationPkgApisClusterregistryV1alpha1ClusterCondition.status) &&
        Objects.equals(this.type, comGithubOpenClusterManagementMulticloudOperatorsFoundationPkgApisClusterregistryV1alpha1ClusterCondition.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastHeartbeatTime, lastTransitionTime, message, reason, status, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubOpenClusterManagementMulticloudOperatorsFoundationPkgApisClusterregistryV1alpha1ClusterCondition {\n");
    
    sb.append("    lastHeartbeatTime: ").append(toIndentedString(lastHeartbeatTime)).append("\n");
    sb.append("    lastTransitionTime: ").append(toIndentedString(lastTransitionTime)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

