/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package open_cluster_management.io;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TagEventCondition contains condition information for a tag event.
 */
@ApiModel(description = "TagEventCondition contains condition information for a tag event.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-18T17:27:50.678+03:00")
public class ComGithubOpenshiftApiImageV1TagEventCondition {
  @SerializedName("generation")
  private Long generation = null;

  @SerializedName("lastTransitionTime")
  private String lastTransitionTime = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("reason")
  private String reason = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("type")
  private String type = null;

  public ComGithubOpenshiftApiImageV1TagEventCondition generation(Long generation) {
    this.generation = generation;
    return this;
  }

   /**
   * Generation is the spec tag generation that this status corresponds to
   * @return generation
  **/
  @ApiModelProperty(required = true, value = "Generation is the spec tag generation that this status corresponds to")
  public Long getGeneration() {
    return generation;
  }

  public void setGeneration(Long generation) {
    this.generation = generation;
  }

  public ComGithubOpenshiftApiImageV1TagEventCondition lastTransitionTime(String lastTransitionTime) {
    this.lastTransitionTime = lastTransitionTime;
    return this;
  }

   /**
   * LastTransitionTIme is the time the condition transitioned from one status to another.
   * @return lastTransitionTime
  **/
  @ApiModelProperty(value = "LastTransitionTIme is the time the condition transitioned from one status to another.")
  public String getLastTransitionTime() {
    return lastTransitionTime;
  }

  public void setLastTransitionTime(String lastTransitionTime) {
    this.lastTransitionTime = lastTransitionTime;
  }

  public ComGithubOpenshiftApiImageV1TagEventCondition message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Message is a human readable description of the details about last transition, complementing reason.
   * @return message
  **/
  @ApiModelProperty(value = "Message is a human readable description of the details about last transition, complementing reason.")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public ComGithubOpenshiftApiImageV1TagEventCondition reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Reason is a brief machine readable explanation for the condition&#39;s last transition.
   * @return reason
  **/
  @ApiModelProperty(value = "Reason is a brief machine readable explanation for the condition's last transition.")
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public ComGithubOpenshiftApiImageV1TagEventCondition status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Status of the condition, one of True, False, Unknown.
   * @return status
  **/
  @ApiModelProperty(required = true, value = "Status of the condition, one of True, False, Unknown.")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public ComGithubOpenshiftApiImageV1TagEventCondition type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type of tag event condition, currently only ImportSuccess
   * @return type
  **/
  @ApiModelProperty(required = true, value = "Type of tag event condition, currently only ImportSuccess")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubOpenshiftApiImageV1TagEventCondition comGithubOpenshiftApiImageV1TagEventCondition = (ComGithubOpenshiftApiImageV1TagEventCondition) o;
    return Objects.equals(this.generation, comGithubOpenshiftApiImageV1TagEventCondition.generation) &&
        Objects.equals(this.lastTransitionTime, comGithubOpenshiftApiImageV1TagEventCondition.lastTransitionTime) &&
        Objects.equals(this.message, comGithubOpenshiftApiImageV1TagEventCondition.message) &&
        Objects.equals(this.reason, comGithubOpenshiftApiImageV1TagEventCondition.reason) &&
        Objects.equals(this.status, comGithubOpenshiftApiImageV1TagEventCondition.status) &&
        Objects.equals(this.type, comGithubOpenshiftApiImageV1TagEventCondition.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(generation, lastTransitionTime, message, reason, status, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubOpenshiftApiImageV1TagEventCondition {\n");
    
    sb.append("    generation: ").append(toIndentedString(generation)).append("\n");
    sb.append("    lastTransitionTime: ").append(toIndentedString(lastTransitionTime)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

