/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package open_cluster_management.io;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * WorkSetStatus describes the work set status
 */
@ApiModel(description = "WorkSetStatus describes the work set status")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-18T17:27:50.678+03:00")
public class ComGithubOpenClusterManagementMulticloudOperatorsFoundationPkgApisMcmV1beta1WorkSetStatus {
  @SerializedName("reason")
  private String reason = null;

  @SerializedName("status")
  private String status = null;

  public ComGithubOpenClusterManagementMulticloudOperatorsFoundationPkgApisMcmV1beta1WorkSetStatus reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Reason is the reason of the status
   * @return reason
  **/
  @ApiModelProperty(value = "Reason is the reason of the status")
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public ComGithubOpenClusterManagementMulticloudOperatorsFoundationPkgApisMcmV1beta1WorkSetStatus status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Status of the work set
   * @return status
  **/
  @ApiModelProperty(value = "Status of the work set")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubOpenClusterManagementMulticloudOperatorsFoundationPkgApisMcmV1beta1WorkSetStatus comGithubOpenClusterManagementMulticloudOperatorsFoundationPkgApisMcmV1beta1WorkSetStatus = (ComGithubOpenClusterManagementMulticloudOperatorsFoundationPkgApisMcmV1beta1WorkSetStatus) o;
    return Objects.equals(this.reason, comGithubOpenClusterManagementMulticloudOperatorsFoundationPkgApisMcmV1beta1WorkSetStatus.reason) &&
        Objects.equals(this.status, comGithubOpenClusterManagementMulticloudOperatorsFoundationPkgApisMcmV1beta1WorkSetStatus.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reason, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubOpenClusterManagementMulticloudOperatorsFoundationPkgApisMcmV1beta1WorkSetStatus {\n");
    
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

