/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package open_cluster_management.io;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * APIResourceReference is a Kubernetes resource type used by a custom resource
 */
@ApiModel(description = "APIResourceReference is a Kubernetes resource type used by a custom resource")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-18T17:27:50.678+03:00")
public class ComGithubOperatorFrameworkOperatorLifecycleManagerPkgApiApisOperatorsV1alpha1APIResourceReference {
  @SerializedName("kind")
  private String kind = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("version")
  private String version = null;

  public ComGithubOperatorFrameworkOperatorLifecycleManagerPkgApiApisOperatorsV1alpha1APIResourceReference kind(String kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Get kind
   * @return kind
  **/
  @ApiModelProperty(required = true, value = "")
  public String getKind() {
    return kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }

  public ComGithubOperatorFrameworkOperatorLifecycleManagerPkgApiApisOperatorsV1alpha1APIResourceReference name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ComGithubOperatorFrameworkOperatorLifecycleManagerPkgApiApisOperatorsV1alpha1APIResourceReference version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(required = true, value = "")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubOperatorFrameworkOperatorLifecycleManagerPkgApiApisOperatorsV1alpha1APIResourceReference comGithubOperatorFrameworkOperatorLifecycleManagerPkgApiApisOperatorsV1alpha1APIResourceReference = (ComGithubOperatorFrameworkOperatorLifecycleManagerPkgApiApisOperatorsV1alpha1APIResourceReference) o;
    return Objects.equals(this.kind, comGithubOperatorFrameworkOperatorLifecycleManagerPkgApiApisOperatorsV1alpha1APIResourceReference.kind) &&
        Objects.equals(this.name, comGithubOperatorFrameworkOperatorLifecycleManagerPkgApiApisOperatorsV1alpha1APIResourceReference.name) &&
        Objects.equals(this.version, comGithubOperatorFrameworkOperatorLifecycleManagerPkgApiApisOperatorsV1alpha1APIResourceReference.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kind, name, version);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubOperatorFrameworkOperatorLifecycleManagerPkgApiApisOperatorsV1alpha1APIResourceReference {\n");
    
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

