/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package open_cluster_management.io;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import open_cluster_management.io.ComGithubOpenshiftApiAppsV1DeploymentCauseImageTrigger;

/**
 * DeploymentCause captures information about a particular cause of a deployment.
 */
@ApiModel(description = "DeploymentCause captures information about a particular cause of a deployment.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-18T17:27:50.678+03:00")
public class ComGithubOpenshiftApiAppsV1DeploymentCause {
  @SerializedName("imageTrigger")
  private ComGithubOpenshiftApiAppsV1DeploymentCauseImageTrigger imageTrigger = null;

  @SerializedName("type")
  private String type = null;

  public ComGithubOpenshiftApiAppsV1DeploymentCause imageTrigger(ComGithubOpenshiftApiAppsV1DeploymentCauseImageTrigger imageTrigger) {
    this.imageTrigger = imageTrigger;
    return this;
  }

   /**
   * ImageTrigger contains the image trigger details, if this trigger was fired based on an image change
   * @return imageTrigger
  **/
  @ApiModelProperty(value = "ImageTrigger contains the image trigger details, if this trigger was fired based on an image change")
  public ComGithubOpenshiftApiAppsV1DeploymentCauseImageTrigger getImageTrigger() {
    return imageTrigger;
  }

  public void setImageTrigger(ComGithubOpenshiftApiAppsV1DeploymentCauseImageTrigger imageTrigger) {
    this.imageTrigger = imageTrigger;
  }

  public ComGithubOpenshiftApiAppsV1DeploymentCause type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type of the trigger that resulted in the creation of a new deployment
   * @return type
  **/
  @ApiModelProperty(required = true, value = "Type of the trigger that resulted in the creation of a new deployment")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubOpenshiftApiAppsV1DeploymentCause comGithubOpenshiftApiAppsV1DeploymentCause = (ComGithubOpenshiftApiAppsV1DeploymentCause) o;
    return Objects.equals(this.imageTrigger, comGithubOpenshiftApiAppsV1DeploymentCause.imageTrigger) &&
        Objects.equals(this.type, comGithubOpenshiftApiAppsV1DeploymentCause.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(imageTrigger, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubOpenshiftApiAppsV1DeploymentCause {\n");
    
    sb.append("    imageTrigger: ").append(toIndentedString(imageTrigger)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

