/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package open_cluster_management.io;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * IngressBackend describes all endpoints for a given service and port.
 */
@ApiModel(description = "IngressBackend describes all endpoints for a given service and port.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-18T17:27:50.678+03:00")
public class IoK8sApiNetworkingV1beta1IngressBackend {
  @SerializedName("serviceName")
  private String serviceName = null;

  @SerializedName("servicePort")
  private String servicePort = null;

  public IoK8sApiNetworkingV1beta1IngressBackend serviceName(String serviceName) {
    this.serviceName = serviceName;
    return this;
  }

   /**
   * Specifies the name of the referenced service.
   * @return serviceName
  **/
  @ApiModelProperty(required = true, value = "Specifies the name of the referenced service.")
  public String getServiceName() {
    return serviceName;
  }

  public void setServiceName(String serviceName) {
    this.serviceName = serviceName;
  }

  public IoK8sApiNetworkingV1beta1IngressBackend servicePort(String servicePort) {
    this.servicePort = servicePort;
    return this;
  }

   /**
   * Specifies the port of the referenced service.
   * @return servicePort
  **/
  @ApiModelProperty(required = true, value = "Specifies the port of the referenced service.")
  public String getServicePort() {
    return servicePort;
  }

  public void setServicePort(String servicePort) {
    this.servicePort = servicePort;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoK8sApiNetworkingV1beta1IngressBackend ioK8sApiNetworkingV1beta1IngressBackend = (IoK8sApiNetworkingV1beta1IngressBackend) o;
    return Objects.equals(this.serviceName, ioK8sApiNetworkingV1beta1IngressBackend.serviceName) &&
        Objects.equals(this.servicePort, ioK8sApiNetworkingV1beta1IngressBackend.servicePort);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serviceName, servicePort);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoK8sApiNetworkingV1beta1IngressBackend {\n");
    
    sb.append("    serviceName: ").append(toIndentedString(serviceName)).append("\n");
    sb.append("    servicePort: ").append(toIndentedString(servicePort)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

