/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package open_cluster_management.io;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import open_cluster_management.io.IoOpenshiftConfigV1OAuthSpecBasicAuthCa;
import open_cluster_management.io.IoOpenshiftConfigV1OAuthSpecGithubClientSecret;

/**
 * gitlab enables user authentication using GitLab credentials
 */
@ApiModel(description = "gitlab enables user authentication using GitLab credentials")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-18T17:27:50.678+03:00")
public class IoOpenshiftConfigV1OAuthSpecGitlab {
  @SerializedName("ca")
  private IoOpenshiftConfigV1OAuthSpecBasicAuthCa ca = null;

  @SerializedName("clientID")
  private String clientID = null;

  @SerializedName("clientSecret")
  private IoOpenshiftConfigV1OAuthSpecGithubClientSecret clientSecret = null;

  @SerializedName("url")
  private String url = null;

  public IoOpenshiftConfigV1OAuthSpecGitlab ca(IoOpenshiftConfigV1OAuthSpecBasicAuthCa ca) {
    this.ca = ca;
    return this;
  }

   /**
   * Get ca
   * @return ca
  **/
  @ApiModelProperty(value = "")
  public IoOpenshiftConfigV1OAuthSpecBasicAuthCa getCa() {
    return ca;
  }

  public void setCa(IoOpenshiftConfigV1OAuthSpecBasicAuthCa ca) {
    this.ca = ca;
  }

  public IoOpenshiftConfigV1OAuthSpecGitlab clientID(String clientID) {
    this.clientID = clientID;
    return this;
  }

   /**
   * clientID is the oauth client ID
   * @return clientID
  **/
  @ApiModelProperty(value = "clientID is the oauth client ID")
  public String getClientID() {
    return clientID;
  }

  public void setClientID(String clientID) {
    this.clientID = clientID;
  }

  public IoOpenshiftConfigV1OAuthSpecGitlab clientSecret(IoOpenshiftConfigV1OAuthSpecGithubClientSecret clientSecret) {
    this.clientSecret = clientSecret;
    return this;
  }

   /**
   * Get clientSecret
   * @return clientSecret
  **/
  @ApiModelProperty(value = "")
  public IoOpenshiftConfigV1OAuthSpecGithubClientSecret getClientSecret() {
    return clientSecret;
  }

  public void setClientSecret(IoOpenshiftConfigV1OAuthSpecGithubClientSecret clientSecret) {
    this.clientSecret = clientSecret;
  }

  public IoOpenshiftConfigV1OAuthSpecGitlab url(String url) {
    this.url = url;
    return this;
  }

   /**
   * url is the oauth server base URL
   * @return url
  **/
  @ApiModelProperty(value = "url is the oauth server base URL")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoOpenshiftConfigV1OAuthSpecGitlab ioOpenshiftConfigV1OAuthSpecGitlab = (IoOpenshiftConfigV1OAuthSpecGitlab) o;
    return Objects.equals(this.ca, ioOpenshiftConfigV1OAuthSpecGitlab.ca) &&
        Objects.equals(this.clientID, ioOpenshiftConfigV1OAuthSpecGitlab.clientID) &&
        Objects.equals(this.clientSecret, ioOpenshiftConfigV1OAuthSpecGitlab.clientSecret) &&
        Objects.equals(this.url, ioOpenshiftConfigV1OAuthSpecGitlab.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ca, clientID, clientSecret, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoOpenshiftConfigV1OAuthSpecGitlab {\n");
    
    sb.append("    ca: ").append(toIndentedString(ca)).append("\n");
    sb.append("    clientID: ").append(toIndentedString(clientID)).append("\n");
    sb.append("    clientSecret: ").append(toIndentedString(clientSecret)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

