/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package open_cluster_management.io;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * projectRequestTemplate is the template to use for creating projects in response to projectrequest. This must point to a template in &#39;openshift-config&#39; namespace. It is optional. If it is not specified, a default template is used.
 */
@ApiModel(description = "projectRequestTemplate is the template to use for creating projects in response to projectrequest. This must point to a template in 'openshift-config' namespace. It is optional. If it is not specified, a default template is used.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-18T17:27:50.678+03:00")
public class IoOpenshiftConfigV1ProjectSpecProjectRequestTemplate {
  @SerializedName("name")
  private String name = null;

  public IoOpenshiftConfigV1ProjectSpecProjectRequestTemplate name(String name) {
    this.name = name;
    return this;
  }

   /**
   * name is the metadata.name of the referenced project request template
   * @return name
  **/
  @ApiModelProperty(value = "name is the metadata.name of the referenced project request template")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoOpenshiftConfigV1ProjectSpecProjectRequestTemplate ioOpenshiftConfigV1ProjectSpecProjectRequestTemplate = (IoOpenshiftConfigV1ProjectSpecProjectRequestTemplate) o;
    return Objects.equals(this.name, ioOpenshiftConfigV1ProjectSpecProjectRequestTemplate.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoOpenshiftConfigV1ProjectSpecProjectRequestTemplate {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

