/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package open_cluster_management.io;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import open_cluster_management.io.IoOpenshiftTunedV1TunedSpecProfile;
import open_cluster_management.io.IoOpenshiftTunedV1TunedSpecRecommend;

/**
 * spec is the specification of the desired behavior of Tuned. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status
 */
@ApiModel(description = "spec is the specification of the desired behavior of Tuned. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-18T17:27:50.678+03:00")
public class IoOpenshiftTunedV1TunedSpec {
  @SerializedName("profile")
  private List<IoOpenshiftTunedV1TunedSpecProfile> profile = new ArrayList<>();

  @SerializedName("recommend")
  private List<IoOpenshiftTunedV1TunedSpecRecommend> recommend = new ArrayList<>();

  public IoOpenshiftTunedV1TunedSpec profile(List<IoOpenshiftTunedV1TunedSpecProfile> profile) {
    this.profile = profile;
    return this;
  }

  public IoOpenshiftTunedV1TunedSpec addProfileItem(IoOpenshiftTunedV1TunedSpecProfile profileItem) {
    this.profile.add(profileItem);
    return this;
  }

   /**
   * Tuned profiles.
   * @return profile
  **/
  @ApiModelProperty(required = true, value = "Tuned profiles.")
  public List<IoOpenshiftTunedV1TunedSpecProfile> getProfile() {
    return profile;
  }

  public void setProfile(List<IoOpenshiftTunedV1TunedSpecProfile> profile) {
    this.profile = profile;
  }

  public IoOpenshiftTunedV1TunedSpec recommend(List<IoOpenshiftTunedV1TunedSpecRecommend> recommend) {
    this.recommend = recommend;
    return this;
  }

  public IoOpenshiftTunedV1TunedSpec addRecommendItem(IoOpenshiftTunedV1TunedSpecRecommend recommendItem) {
    this.recommend.add(recommendItem);
    return this;
  }

   /**
   * Selection logic for all tuned profiles.
   * @return recommend
  **/
  @ApiModelProperty(required = true, value = "Selection logic for all tuned profiles.")
  public List<IoOpenshiftTunedV1TunedSpecRecommend> getRecommend() {
    return recommend;
  }

  public void setRecommend(List<IoOpenshiftTunedV1TunedSpecRecommend> recommend) {
    this.recommend = recommend;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoOpenshiftTunedV1TunedSpec ioOpenshiftTunedV1TunedSpec = (IoOpenshiftTunedV1TunedSpec) o;
    return Objects.equals(this.profile, ioOpenshiftTunedV1TunedSpec.profile) &&
        Objects.equals(this.recommend, ioOpenshiftTunedV1TunedSpec.recommend);
  }

  @Override
  public int hashCode() {
    return Objects.hash(profile, recommend);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoOpenshiftTunedV1TunedSpec {\n");
    
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("    recommend: ").append(toIndentedString(recommend)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

