/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package open_cluster_management.io;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * status holds observed values from the cluster. They may not be overridden.
 */
@ApiModel(description = "status holds observed values from the cluster. They may not be overridden.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-18T17:27:50.678+03:00")
public class IoOpenshiftConfigV1ConsoleStatus {
  @SerializedName("consoleURL")
  private String consoleURL = null;

  public IoOpenshiftConfigV1ConsoleStatus consoleURL(String consoleURL) {
    this.consoleURL = consoleURL;
    return this;
  }

   /**
   * The URL for the console. This will be derived from the host for the route that is created for the console.
   * @return consoleURL
  **/
  @ApiModelProperty(value = "The URL for the console. This will be derived from the host for the route that is created for the console.")
  public String getConsoleURL() {
    return consoleURL;
  }

  public void setConsoleURL(String consoleURL) {
    this.consoleURL = consoleURL;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoOpenshiftConfigV1ConsoleStatus ioOpenshiftConfigV1ConsoleStatus = (IoOpenshiftConfigV1ConsoleStatus) o;
    return Objects.equals(this.consoleURL, ioOpenshiftConfigV1ConsoleStatus.consoleURL);
  }

  @Override
  public int hashCode() {
    return Objects.hash(consoleURL);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoOpenshiftConfigV1ConsoleStatus {\n");
    
    sb.append("    consoleURL: ").append(toIndentedString(consoleURL)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

