/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package open_cluster_management.io;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * HubSourceStatus is used to reflect the current state of applying the configuration to a default source
 */
@ApiModel(description = "HubSourceStatus is used to reflect the current state of applying the configuration to a default source")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-18T17:27:50.678+03:00")
public class IoOpenshiftConfigV1OperatorHubStatusSources {
  @SerializedName("disabled")
  private Boolean disabled = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("status")
  private String status = null;

  public IoOpenshiftConfigV1OperatorHubStatusSources disabled(Boolean disabled) {
    this.disabled = disabled;
    return this;
  }

   /**
   * disabled is used to disable a default hub source on cluster
   * @return disabled
  **/
  @ApiModelProperty(value = "disabled is used to disable a default hub source on cluster")
  public Boolean isDisabled() {
    return disabled;
  }

  public void setDisabled(Boolean disabled) {
    this.disabled = disabled;
  }

  public IoOpenshiftConfigV1OperatorHubStatusSources message(String message) {
    this.message = message;
    return this;
  }

   /**
   * message provides more information regarding failures
   * @return message
  **/
  @ApiModelProperty(value = "message provides more information regarding failures")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public IoOpenshiftConfigV1OperatorHubStatusSources name(String name) {
    this.name = name;
    return this;
  }

   /**
   * name is the name of one of the default hub sources
   * @return name
  **/
  @ApiModelProperty(value = "name is the name of one of the default hub sources")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public IoOpenshiftConfigV1OperatorHubStatusSources status(String status) {
    this.status = status;
    return this;
  }

   /**
   * status indicates success or failure in applying the configuration
   * @return status
  **/
  @ApiModelProperty(value = "status indicates success or failure in applying the configuration")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoOpenshiftConfigV1OperatorHubStatusSources ioOpenshiftConfigV1OperatorHubStatusSources = (IoOpenshiftConfigV1OperatorHubStatusSources) o;
    return Objects.equals(this.disabled, ioOpenshiftConfigV1OperatorHubStatusSources.disabled) &&
        Objects.equals(this.message, ioOpenshiftConfigV1OperatorHubStatusSources.message) &&
        Objects.equals(this.name, ioOpenshiftConfigV1OperatorHubStatusSources.name) &&
        Objects.equals(this.status, ioOpenshiftConfigV1OperatorHubStatusSources.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(disabled, message, name, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoOpenshiftConfigV1OperatorHubStatusSources {\n");
    
    sb.append("    disabled: ").append(toIndentedString(disabled)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

